# Generated by Django 5.1.4 on 2024-12-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='projects/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Graded', 'Graded')], default='Pending', max_length=10)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('grading_note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
