# Generated by Django 5.1.4 on 2024-12-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subforum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.URLField(max_length=500),
        ),
    ]
