# Generated by Django 5.1.4 on 2024-12-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subforum', '0004_alter_projects_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
