# Generated by Django 5.1.4 on 2024-12-15 19:21

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subforum', '0004_remove_projects_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=''),
        ),
    ]
