# Generated by Django 5.1.4 on 2024-12-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subforum', '0005_alter_projects_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
